version: '3.1'
services:

  nginx:
    shm_size: 64mb
    image: nginx:1-alpine
    depends_on:
      - wordpress
    ports:
      - ${PORT}:80
    volumes:
      - ./conf/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - wordpress:/var/www/html
      - .:/var/www/html/wp-content/themes/vanilla
      - .:/home/www-data/app

  # WordPress
  #
  wordpress:
    shm_size: 256mb
    image: wordpress:fpm-alpine
    depends_on:
      - mysql
    environment:
      WORDPRESS_DB_PASSWORD: wordpress
      ABSPATH: /usr/src/wordpress/
    volumes:
      - wordpress:/var/www/html
      - .:/var/www/html/wp-content/themes/vanilla

  site-perms-helper:
    image: alpine:3.8
    depends_on:
      - wordpress
    restart: "no"
    volumes:
      - wordpress:/var/www/html
      - .:/var/www/html/wp-content/themes/vanilla
    command: /bin/ash -c "chmod 767 /var/www/html/wp-content && chmod 767 /var/www/html/wp-content/plugins"

  cli:
    image: wordpress:cli
    depends_on:
      - site-perms-helper
    volumes:
      - ./bin:/opt/bin
      - wordpress:/var/www/html
      - .:/var/www/html/wp-content/themes/vanilla
    command: >
      sh /opt/bin/wait-for.sh mysql:3306 -t 60 -- sh /opt/bin/install.sh $PORT

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: wordpress
      MYSQL_DATABASE: wordpress_test

volumes:
  testsuite:
  wordpress:
