version: '3.1'
services:
  wordpress:
    image: wordpress
    depends_on:
      - mysql
    ports:
      - ${PORT}:80
    environment:
      WORDPRESS_DB_PASSWORD: wordpress
      ABSPATH: /usr/src/wordpress/
    volumes:
      - wordpress:/var/www/html
      - .:/var/www/html/wp-content/themes/vanilla

  cli:
    image: wordpress:cli
    user: xfs
    volumes:
      - ./bin:/opt/bin
      - wordpress:/var/www/html
      - .:/var/www/html/wp-content/themes/vanilla
    depends_on:
      - mysql
      - wordpress
    command: >
      sh /opt/bin/wait-for.sh mysql:3306 -t 60 -- sh /opt/bin/install.sh $PORT

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: wordpress
      MYSQL_DATABASE: wordpress_test

  wordpress_phpunit:
    image: chriszarate/wordpress-phpunit
    environment:
      PHPUNIT_DB_HOST: mysql
    volumes:
      - .:/app
      - testsuite:/tmp

  composer:
    image: composer
    volumes:
      - .:/app

  node:
    image: node
    working_dir: /app
    volumes:
      - .:/app

  backstopjs:
    shm_size: 2gb
    image: torounit/backstopjs-noto
    network_mode: host
    volumes:
      - .:/src
#    depends_on:
#      - mysql
#      - wordpress

volumes:
  testsuite:
  wordpress:
