version: 2.0
jobs:
  build:
    # The primary container is an instance of the first list image listed. Your build commands run in this container.
    docker:
      - image: torounit/wp-theme-test:0.0.2
    working_directory: /var/www/wordpress/wp-content/themes/vanilla
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - restore_cache:
          key: dependency-cache-{{ checksum "composer.json" }}
      - run:
          command: node -v
      - run:
          command: ls /var/www
      - run:
          name: Install npm
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - node_modules
      - run:
          name: build
          command: npm run build
      - run:
          name: Install Composer
          command: composer install
      - save_cache:
          key: dependency-cache-{{ checksum "composer.json" }}
          paths:
            - vendor
      - run:
          command: sudo service php7.0-fpm start
      - run:
          command: sudo service nginx start
      - run:
          command: sudo service mysql start
      - run:
          name: wp
          command: wp theme activate vanilla --path=/var/www/wordpress
  test:
    docker:
      - image: torounit/wp-theme-test:0.0.1
    steps:
      - checkout
      - run:
          name: PHP Test
          command: composer test
      - run:
          name: Test
          command: npm test
      - store_artifacts:
          path: backstop_data/ci_report/xunit.xml
          prefix: tests
